# Generated by Django 3.1.2 on 2021-11-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211105_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['header']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='header',
        ),
    ]
