# Generated by Django 3.1.2 on 2021-11-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211105_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='body',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='header',
            new_name='title',
        ),
    ]
